### ISSUE TITLE
aretomo2relion: wrong bad reconstruction, wrong FullImage params

### ISSUE THREAD

**Issue by MoritzWM** [tomotools/tomotools#18]
Just tested aretomo2relion and found a bug: the reconstructions created by the function are very terrible.
When I tested relion_tomo_reconstruct_tomogram, the reconstruction was better, but still not good and also had the  wrong aspect ratio, namely width and height were swapped (same for the Imod reconstruction).

The tilt.com file has the FullImage param which was wrong: when I changed it from `FULLIMAGE 5760 4092` to `FULLIMAGE 4092 5760`, re-imported and re-reconstructed in relion, all was fine.

I'm not sure where this file is created, is this done by aretomo?

**Comment by bwmr** [comment]
Thanks for catching this! - something I missed due to our almost-square K2 sensor ;) the tilt.com is generated by AreTomo during export. The fix should be relatively easy to implement:

1. I wrote a function to return the correct output dimensions (taking tilt axis into account), which so far is only used in generating a stack using ```newstack```: ```tiltseries.binned_size()```: commit [58be74d](https://github.com/tomotools/tomotools/commit/58be74dcedf7d79af533d4de2ca430079f0670a2) 
2. For the 3D CTF reconstruction in the STOPGAP flow, I already wrote the comfile.fix_tiltcom function ([commit](https://github.com/tomotools/tomotools/commit/fe5b57e559e451f89516c2e665034e03335047e7)), this should be called also during Relion export and additionally write the correct output size.

**Comment by bwmr** [comment]
I now adapted comfile.fix_tiltcom() to set the correct FULLIMAGE size, which right now needs to be passed to the function to avoid issues with binning etc. Commit 5b17299.

Remaining ToDos:
- [ ] make sure aretomo2relion calls fix_tiltcom().

**Comment by bwmr** [comment]
@MoritzWM maybe I'll close this issue and remove the relion4 branch, since Relion 5 anyways seems to work differently?

**Comment by MoritzWM** [comment]
Yes I think that's a good idea. I suppose there's not much sense in putting too much effort into Relion 4 support when there's Relion 5 available
